version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "988253048728"
    AWS_REGION: "us-east-1"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - IMAGE_TAG=$(jq -r ".version" package.json)
      - npm run d:b

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mainserver
